In [ ]:
# 1)Underfitting:-
# Underfitting is when a machine learning model is too simple to learn the important patterns in the data.
# It performs poorly on both the training data and new data.
# increase no.of feature/increase complexity
# Training accuracy is low and Testing accuracy is low

# Model is too basic
# Misses key patterns
# High error on training and testing

# 2)Overfitting
# Overfitting is when a machine learning model learns the training data too well, including noise and random fluctuations.
# It performs very well on training data but poorly on new data.
# increase no.of feature/increase complexity
# Training accuracy is high and Testing accuracy is low

# Model is too complex
# Learns noise instead of general pattern
# Low training error, high test error

In [2]:
# Bias-Variance Tradeoff 
# Bias-variance tradeoff is the balance between:

# Bias: error due to a model being too simple
# Variance: error due to a model being too complex
# Relationship
# More complexity → lower bias, higher variance
# Less complexity → higher bias, lower variance

In [3]:
# Regularisation algorithm is used for reducing under & overfiting situation.
# ->we have two types of Regularisation
# 1]Lasso(L1)
# 2]Ridge(L2)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,root_mean_squared_error
from sklearn.preprocessing import StandardScaler

In [5]:
df=pd.read_csv("C:/Users/swaru/OneDrive/Desktop/ML/Session2/Advertising.csv")

In [6]:
df

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [7]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [9]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [20]:
# step2:-print information of data

In [13]:
print("first 5 rows")
print(df.head())

print("shape od dataset")
print(df.shape)

print("dataset information")
print(df.info())

print("Statistical summary")
print(df.describe())

print("null values counting")
print(df.isnull().sum())

first 5 rows
      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9
shape od dataset
(200, 4)
dataset information
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB
None
Statistical summary
               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000
null values counting
TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [14]:
# step3:-Seperate  dependent and independent variable

In [16]:
X=df.drop("Sales",axis=1)
y=df['Sales']

In [17]:
# step4:-train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
# step5:-Apply standard scaler on numerical data

In [24]:
ss=StandardScaler()

In [ ]:
X_train_scaled=ss.fit_transform(X_train)
X_test_scaled=ss.transform(X_test)

# fit transform=learns the data's parameter and after that apply transformation
# Transform = only apply transformation using parameters that were already learned

In [26]:
# step6:-Apply algorithm multiple linear regression

In [27]:
lr= LinearRegression()

In [28]:
lr.fit(X_train_scaled,y_train)

LinearRegression()

In [29]:
lr.coef_

array([3.76419618, 2.79230665, 0.05597551])

In [30]:
y_pred=lr.predict(X_train_scaled)

In [33]:
# training score

In [32]:
r2_score(y_pred,y_train)

0.8835557925789809

In [34]:
# testing score

In [35]:
y_predict=lr.predict(X_test_scaled)

In [36]:
r2_score(y_test,y_predict)

0.8994380241009119

In [37]:
# step7:-Ridge Regression

In [39]:
from sklearn.linear_model import Ridge
ridge=Ridge(1.0)

In [40]:
ridge.fit(X_train_scaled,y_train)

Ridge()

In [41]:
ridge.coef_

array([3.74169256, 2.77331224, 0.0633801 ])

In [42]:
y_pred=ridge.predict(X_test_scaled)

In [43]:
r2_score(y_test,y_pred)

0.8988025280800618

In [49]:
for alpha in range(1,5):
    l2=Ridge(alpha)
    l2.fit(X_train_scaled,y_train)
    train_score=l2.score(X_train_scaled,y_train)
    print("----------------------")
    print(train_score)
    test_score=l2.score(X_test_scaled,y_test)
    print(f"test score={test_score}")

----------------------
0.8956679557030848
test score=0.8988025280800618
----------------------
0.8955710870941749
test score=0.898118490797406
----------------------
0.8954127559026344
test score=0.8973880106308303
----------------------
0.8951953896125463
test score=0.8966130922940985

In [51]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.1)
lasso.fit(X_train_scaled,y_train)

Lasso(alpha=0.1)

In [52]:
lasso.coef_

array([3.66920574, 2.71914667, 0.        ])

In [53]:
y_predict=lasso.predict(X_train_scaled)

In [54]:
r2_score(y_train,y_predict)

0.8948665120975132

In [55]:
y_pred=lasso.predict(X_test_scaled)

In [56]:
r2_score(y_test,y_pred)

0.8983361384489736

In [58]:
coefficient=pd.DataFrame({
    'Features':X.columns,
    "Linear":lr.coef_,
    "Ridge":ridge.coef_,
    "Lasso":lasso.coef_
})

In [59]:
coefficient

    Features    Linear     Ridge     Lasso
0         TV  3.764196  3.741693  3.669206
1      Radio  2.792307  2.773312  2.719147
2  Newspaper  0.055976  0.063380  0.000000